### ISSUE TITLE
Fail to load on HA 2023.6.2

### ISSUE THREAD

**Issue by haaino** [denysdovhan/purifier-card#229]
Hi,

I just installed version 2.3.0 on HA 2023.6.2.

For some reason the card has "disappeared" from the list of selectable cards and my configured instance does not load anymore.

I'm getting the following error message: "Custom element does not exist:purifier-card".

I hope you can investigate. I would highly appreciate it. Let me know if I can assist in any way.

Best regards,
Haaino

**Comment by oopiicaa** [comment]
This is the same as https://github.com/denysdovhan/purifier-card/issues/228 - it is supposed to be fixed with 2.3.1, so you can try with this version (should be available through manual download via HACS). It does not work for me though - the issue is still the same in 2.3.1 and only downgrading to 2.2.3 fixes it.

**Comment by haaino** [comment]
Hi,

Sorry, I missed the similair issue. 

I have manually updated to v 2.3.1, it does resolve it for me fortunatly.

I will close this issue because it already exist with #228

Thank you for your great and quick response
